### ISSUE TITLE
BlanketJS Intergration

### ISSUE THREAD

**Issue by ravilution** [dominiklessel/node-restify-boilerplate#4]
Hi,

Tried adding blanket with below configuration. It does not seem to be working.

``
  "config": {
      "blanket": {
        "pattern": [ "" ],
        "data-cover-never": [ "node_modules" , "tests"]
      }
    }
``

Added below line in the Makefile

``
@NODE_ENV=test ./node_modules/.bin/mocha --require blanket -R html-cov > coverage.html
``

Coverage.html gets created. But it shows 0% coverage 0 SLOC

@ravilution

**Comment by dominiklessel** [comment]
@ravilution Sorry for the huge delay! I totally missed your issue ... I've never worked with BlanketJS, so please feel free to open an PR.
